### ISSUE TITLE
Mercurial missing in 2020.1.2 images

### ISSUE THREAD

**Issue by frankschierle** [JetBrains/teamcity-docker-agent#71]
Hi,
in my company we are using the TeamCity docker images provided by JetBrains as base images for our own images. I just upgraded our 2020.1.1 images to 2020.1.2. The only change i made, was to replace the base image: `FROM jetbrains/teamcity-agent:2020.1.1-windowsservercore` -> `FROM jetbrains/teamcity-agent:2020.1.2-windowsservercore`.

I discovered that Mercurial is missing in the 2020.1.2 image:
![TC_202011_202022](https://user-images.githubusercontent.com/21262852/87660556-8aa34d80-c75f-11ea-80be-a5f75b8444ce.png)

It's not mentioned in the release notes, that mercurial support has been removed. The DOCKERFILEs, provided here, still contain the install instructions for mercurial. So why is it missing?

**Comment by dmitry-treskunov** [comment]
Hi, we removed Mercurial from windows Docker images because BitBucket deprecated Mercurial repositories and removed the Mercurial installer which we used.

Please see our Upgrade notes: https://www.jetbrains.com/help/teamcity/upgrade-notes.html#UpgradeNotes-Changesfrom2020.1.1to2020.1.2

As a workaround consider using the previous version of the agent image if you need Mercurial (agents should auto-upgrade on start).

**Comment by frankschierle** [comment]
Hi, thanks for the reply.

I have only read the Relase Notes - sorry, my fault.

As a workaround i installed Mercurial in our custom images using an installer provided by the Mercurial developers themselves. You can get it at https://www.mercurial-scm.org/release/windows/.
I think it would be an option to use these installers to bring back Mercurial support in future versions of your images.

Apart from that I think it would make sense to update the DOCKERFILEs provided in this repository. As mentioned earlier, they still contain the code to install Mercurial. So the currently available images on docker hub obviously could not have been created using these files.

**Comment by dmitry-treskunov** [comment]
Thanks, we'll consider adding Mercurial back

And you are right, this repository is an obsolete one, we'll update it soon

**Comment by ghost** [comment]
> Thanks, we'll consider adding Mercurial back
> 
> And you are right, this repository is an obsolete one, we'll update it soon

How soon is soon? Just tried rebuilding our images and ran into the mercurial issue as well. It's been over a month since the last post.

If I can't trust this repository as a source of truth, then I'll work with our TeamCity account manager to fix that. 

Update: Nevermind, I see that this repository was deprecated.

**Comment by NikolayPianikov** [comment]
@brogers-navex sorry for delay, fixed and will be available next week

FYI: [new repo](https://github.com/JetBrains/teamcity-docker-images)

**Comment by NikolayPianikov** [comment]
https://youtrack.jetbrains.com/issue/TW-67553
